
exports.errorCodeToExplanation = {
    "A3": "Missing line break at end of file.",
    "C1": "Too many conditional branchings.",
    "C3": "Forbidden keyword: goto.",
    "F2": "Function names should be in snake case.",
    "F3": "Lines should not exceed 80 characters.",
    "F4": "Functions should not exceed 20 lines.",
    "F5": "Functions should not have more than 4 arguments.",
    "F6": "Functions taking no arguments should take void as their only argument.",
    "F8": "Functions should not contain any comment.",
    "F9": "Forbidden feature: nested functions.",
    "G1": "Corrupted Epitech header.",
    "G2": "One and only one empty line should be present between functions.",
    "G3": "Badly indented pre-processor directive.",
    "G4": "Global variables should be marked as const.",
    "G5": "include directive must only include C header (.h) files.",
    "G6": "Line endings must be done in UNIX style (with \n).",
    "G7": "No trailing spaces must be present at the end of a line.",
    "G8": "No leading empty lines must be present and no more than 1 trailing empty line must be present.",
    "H1": "Header files must only contain function prototypes, type declarations, global variable/constant declarations, macros and static inline functions.",
    "H2": "Headers must be protected from double inclusion.",
    "L2": "Each indentation level must be done by using 4 spaces, and no tabulations may be used for identation.",
    "L3": "Misplaced space.",
    "L4": "Misplaced curly-bracket.",
    "O1": "The repository must not contain compiled (.o, .gch, .a, .so, ...), temporary or unnecessary files (*~, #*#, .d, toto, ...)",
    "O3": "A source file must match a logical entity, and group all the functions associated with that entity.",
    "O4": "The name of the file must define the logical entity it represents, and thus be clear, precise, explicit and unambiguous.",
    "V1": "All identifier names must be in English, according to the snake_case convention."
};
