name: Generate changelog

on:
  pull_request:
    branches: [ master, main ]
    types: [opened, reopened]

jobs:
  gen-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/
      - name: Install nodejs
        run: sudo apt install nodejs

      - name: Gen changelog and update version
        shell: bash
        run: |
          echo "${{ github.event.pull_request.title }}" > pr_msg
          echo "${{ github.event.pull_request.body }}" > pr_body
          python genChangelog.py > CHANGELOG.md
          node updateVersion.js

      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: |
            ${{ github.event.pull_request.title }}

            ${{ github.event.pull_request.body }}