name: "Publish new version"
on:
  push:
    branches:
      - main
jobs:
  check:
    name: "Run tests"
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: |
          (cd tests && ./runTests) || true

  deploy:
    name: "Publish the new version"
    runs-on: ubuntu-latest
    needs: [check]
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/

      - name: Install the dependencies
        run: sudo apt install nodejs && npm i

      - name: Install vsce
        run: npm i -g vsce

      # - name: Generate CHANGELOG
      #   run: |
      #     python workflow_scripts/genChangelog.py > CHANGELOG.md
      #     python workflow_scripts/genChangelog.py >> README.md
      #     node workflow_scripts/updateVersion.js

      # - name: Pre-publish
      #   run: |
      #     git config --global user.email "quentin.desmettre@epitech.eu"
      #     git config --global user.name "Quentin-Desmettre"
      #     git add . && git commit -m "chore: Publishing extension"


      - name: Publish
        run: |
          vsce publish -p ${{ secrets.PUBLISHER_KEY }}